# Generated by Django 5.2.6 on 2025-09-27 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('signup_date', models.DateField()),
                ('last_purchase_date', models.DateField()),
                ('cancellations_count', models.IntegerField(default=0)),
                ('subscription_status', models.CharField(max_length=20)),
                ('purchase_frequency', models.IntegerField(default=0)),
                ('ratings', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=50)),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('test_data_size', models.IntegerField()),
            ],
            options={
                'db_table': 'model_performance',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('unit_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churn_probability', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_predictions', to='analytics.customer')),
            ],
            options={
                'db_table': 'churn_predictions',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='analytics.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='analytics.product')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_quantity', models.IntegerField()),
                ('confidence_level', models.FloatField()),
                ('forecast_period', models.CharField(max_length=20)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_forecasts', to='analytics.product')),
            ],
            options={
                'db_table': 'sales_forecasts',
            },
        ),
    ]
